version: "3"

services:
  app:
    image: teko-crm
    build: .
    networks:
      - crm
    container_name: teko-crm
    ports:
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - mysql
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: crm
    networks:
      - crm
    image: mysql:8.0.20
    container_name: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  crm:
    driver: bridge